FROM alpine:latest AS builder

ARG GO_VERSION=1.25.12
RUN apk add --no-cache ca-certificates curl tar && \
    case "$(apk --print-arch)" in \
      x86_64) GO_ARCH=amd64; GO_SHA256=234828b7a89e0e303d2556310ee549fbcf253d28de937bac3da13d6294262ac1 ;; \
      aarch64) GO_ARCH=arm64; GO_SHA256=8b5884aef89600aef5b0b051fb971f11f49bb996521e911f30f02a66884f7bd2 ;; \
      *) echo "unsupported architecture: $(apk --print-arch)" >&2; exit 1 ;; \
    esac && \
    curl --fail --location --retry 3 \
      "https://golang.google.cn/dl/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz" \
      --output /tmp/go.tar.gz && \
    echo "${GO_SHA256}  /tmp/go.tar.gz" | sha256sum -c - && \
    tar -C /usr/local -xzf /tmp/go.tar.gz && \
    rm /tmp/go.tar.gz

ENV PATH="/usr/local/go/bin:${PATH}" \
    CGO_ENABLED=0 \
    GOTOOLCHAIN=local \
    GOPROXY="https://mirrors.aliyun.com/goproxy/" \
    GOSUMDB="sum.golang.google.cn"

WORKDIR /usr/local/src
COPY . .

RUN apk add --no-cache \
    protobuf \
    protobuf-dev \
    protoc \
    make \
    libcap

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11 &&\
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.2 &&\
    PATH="$PATH:$(go env GOPATH)/bin" make proto &&\
    go build -o octo-cdn ./cmd/octo-cdn &&\
    setcap cap_net_bind_service=+ep ./octo-cdn

FROM alpine:latest

WORKDIR /opt/octo-cdn

RUN chown 1000:1000 /opt/octo-cdn

USER 1000

COPY --from=builder /usr/local/src/octo-cdn .

ENTRYPOINT ["./octo-cdn"]
