FROM alpine:latest AS builder

WORKDIR /usr/local/src
COPY . .

RUN apk add --no-cache go

RUN go build -trimpath -ldflags="-s -w" -o auth-server ./cmd/auth-server && \
    go build -trimpath -ldflags="-s -w" -o account-admin ./cmd/account-admin

FROM alpine:latest

WORKDIR /opt/auth-server

RUN chown 1000:1000 /opt/auth-server

USER 1000

COPY --from=builder /usr/local/src/auth-server .
COPY --from=builder /usr/local/src/account-admin .

ENTRYPOINT ["./auth-server"]
