package service

var gachaWebText = map[string]map[string]string{
	"en": {
		"title": "Summon Details", "rates": "Drop Rates", "rarity": "Rarity", "reward": "Reward", "weapon": "Weapon",
		"characterWeapon": "With character", "weaponOnly": "Weapon only", "groups": "Rates by rarity",
		"normalSlots": "10x Summon: draws 1–9 / Single Summon", "tenthSlot": "10x Summon: draw 10",
		"multiNormalSlots": "10x Summon: draws 1–9",
		"individualRates":  "Individual drop rates", "dropRate": "Drop rate",
		"drawNote":       "Each draw is performed using the rates shown above.",
		"singleNote":     "Performing ten Single Summons does not grant the 10th-draw guarantee of a 10x Summon.",
		"attribute_dark": "Dark", "attribute_fire": "Fire", "attribute_light": "Light", "attribute_none": "Neutral", "attribute_water": "Water", "attribute_wind": "Wind",
		"weapon_sword": "1H sword", "weapon_spear": "Spear", "weapon_bigsword": "2H sword", "weapon_fist": "Fist", "weapon_staff": "Staff", "weapon_gun": "Gun",
		"slot": "Draw %d", "slots": "Draws %d–%d", "draws": "%d draw(s)", "ticket": "Ticket", "phase": "Summon option",
		"refresh": "Refresh", "box": "Current Box", "remaining": "Remaining / total",
		"quantity": "Per draw", "probability": "Next draw", "pickup": "RATE UP",
		"updated": "Updated", "reset": "Next monthly reset", "gems": "Gems",
		"premiumNote": "Each table shows the chance for one draw in the indicated positions, including the selected summon option's guarantee. A character and its paired weapon are one result and share a single drop rate.",
		"boxNote":     "Rates apply to the next draw and change as limited rewards are taken. Remaining counts are the number of draws available, not the number of items received.",
		"chapterNote": "Rates reflect the current limited and unlimited reward pools. When a pool is exhausted, the remaining eligible pool receives 100%. Monthly limits reset at 00:00 UTC−8 on the first day of each month.",
		"rounding":    "Percentages are rounded to six decimal places; displayed totals may differ slightly from 100%.",
		"session":     "Your session has expired or is missing. Return to the game and reopen these details.",
		"invalid":     "This summon link is invalid. Please reopen it from the game.", "missing": "This summon is no longer available.",
		"unavailable": "Summon details are temporarily unavailable. Please try again.",
	},
	"ja": {
		"title": "ガチャ詳細", "rates": "提供割合", "rarity": "レアリティ", "reward": "報酬", "weapon": "出現武器",
		"characterWeapon": "キャラ付き", "weaponOnly": "武器のみ", "groups": "レアリティ別の提供割合",
		"normalSlots": "「10回」ガチャの1〜9枠目および「1回」ガチャ", "tenthSlot": "「10回」ガチャの10枠目",
		"multiNormalSlots": "「10回」ガチャの1〜9枠目",
		"individualRates":  "個別提供割合", "dropRate": "出現率",
		"drawNote":       "※1回ごとに、その提供割合に基づいて抽選を行っております。",
		"singleNote":     "※「1回」ガチャを10回引いた場合でも、その10回目は「10回」ガチャの確定枠の対象にはなりません。",
		"attribute_dark": "闇", "attribute_fire": "火", "attribute_light": "光", "attribute_none": "無", "attribute_water": "水", "attribute_wind": "風",
		"weapon_sword": "小型剣", "weapon_spear": "槍", "weapon_bigsword": "大型剣", "weapon_fist": "格闘", "weapon_staff": "杖", "weapon_gun": "銃",
		"slot": "%d枠目", "slots": "%d〜%d枠目", "draws": "%d回ガチャ", "ticket": "チケット", "phase": "ガチャの種類",
		"refresh": "更新", "box": "現在のBox", "remaining": "残り / 総数",
		"quantity": "1回の獲得数", "probability": "次の1回の確率", "pickup": "出現率UP",
		"updated": "更新日時", "reset": "次回リセット", "gems": "ジェム",
		"premiumNote": "各表は該当する枠の1回あたりの確率です。選択したガチャの確定枠を反映しています。キャラと付属武器は1組の抽選結果で、共通の出現率を表示しています。",
		"boxNote":     "次の1回の抽選確率を表示しています。残りの報酬に応じて確率は変化します。残数は獲得できる回数で、アイテムの個数ではありません。",
		"chapterNote": "数量限定・無制限の各報酬の現在の提供割合を表示しています。一方の報酬がなくなると、抽選対象の残りの報酬が100%になります。月間の残数は毎月1日 00:00（UTC−8）にリセットされます。",
		"rounding":    "確率は小数点以下6桁に丸めて表示しているため、合計が100%にならない場合があります。",
		"session":     "セッションを確認できません。ゲームに戻り、詳細画面を開き直してください。",
		"invalid":     "ガチャの指定が正しくありません。ゲームから開き直してください。", "missing": "このガチャは現在利用できません。",
		"unavailable": "ガチャ詳細を取得できませんでした。時間をおいて再度お試しください。",
	},
}
